image: python:3.13-alpine

stages:
  - build

variables:
  PIP_DISABLE_PIP_VERSION_CHECK: "1"

before_script:
  - apk update
  - apk add --no-cache \
      inkscape \
      texlive \
      texlive-latexextra \
      texmf-dist-latexmk \
      make \
      git \
      py3-pip \
      musl-dev \
      gcc \
      libffi-dev \
      python3-dev
  - pip install sphinx

build_manual:
  stage: build
  script:
    - make
  artifacts:
    paths:
      - output/
    expire_in: 1 week
