image: python:3.13-alpine

stages:
  - build

variables:
  PIP_DISABLE_PIP_VERSION_CHECK: "1"

before_script:
  - apk update
  - apk add --no-cache inkscape
  - apk add --no-cache texlive
  - apk add --no-cache texlive-latexextra
  - apk add --no-cache make
  - apk add --no-cache git
  - apk add --no-cache py3-pip
  - apk add --no-cache musl-dev
  - apk add --no-cache gcc
  - apk add --no-cache libffi-dev
  - apk add --no-cache python3-dev
  - pip install sphinx

build_manual:
  stage: build
  script:
    - make
  artifacts:
    paths:
      - output/
    expire_in: 1 week
