image: python:3.13-slim

stages:
  - build

variables:
  DEBIAN_FRONTEND: noninteractive
  PIP_DISABLE_PIP_VERSION_CHECK: "1"

before_script:
  - apt-get update
  - apt-get install -y --no-install-recommends inkscape
  - apt-get install -y make gcc build-essential
  - pip install --upgrade pip
  - pip install sphinx

build_manual:
  stage: build
  script:
    - make
    - inkscape --version
    - man inkscape
  artifacts:
    paths:
      - output/
    expire_in: 1 week
